### ISSUE TITLE
Več delov vhoda / izhoda

### ISSUE THREAD

**Issue by k3ap** [mucamaca/priprave#5]
Zlasti na začetku želi človek imeti programe interaktivne, nekaj takega:

```c++
printf("Napisi dve stevilki.\n");
scanf("%d%d", &a, &b);
printf("vsota je %d\n", a+b);
```

Pri pisanju vhoda/izhoda takem primeru bi bila optimalna rešitev, da bi imeli dve "izhodni" polji - eno na začetku, eno na koncu; torej nekaj takega:

```tex
\begin{inout}
Napisi dve stevilki
\tcblower
3 7
\tcblower
vsota je 10
\end{inout}
```

Zgornja koda pa sredinski del (3 7) požre, ne da bi ga napisala. Moram za mejo uporabiti kaj drugega kot `\tcblower`?

**Comment by mucamaca** [comment]
`\tcblower` je vec kot samo ukaz za izrisat crto. Naceloma ti colorboxi podpirajo dva sloga na en box - enega za "zgornji del" in enega za "spodnji del". `\tcblower` tudi vklopi slog za spodnji del. Za narisat dodatne crte sem nasel [en answer.](https://tex.stackexchange.com/questions/68010/how-to-create-multilevel-colored-boxes-using-tcolorbox-any-other-package)`.

> Zlasti na začetku želi človek imeti programe interaktivne

Jaz bi reku da zelis takih programov cim manj, ker je treba otroke cimprej nauciti da stdin in stdout nimata nobenega implicitnega orderinga glede na drug drugega. V prvem poglavju stvari je ena taka stvar in lahko pogledas kako je narejena, za naprej se mi pa zdi da je bolje ce se temu izognemo.

**Comment by k3ap** [comment]
Tudi prav. Fejst bodte
